"""USFM Bibles: extract verses, and align a translation to a work by verse number.

Verse numbering is shared across Bibles, so a translation aligns to the source text exactly,
one span per verse, with no hand work. `weft align <work>` writes sense/<translation>.yaml for
every translation whose manifest entry says `format: usfm`.
"""
from __future__ import annotations

import re
from pathlib import Path

import yaml


def verses(path: Path, chapter: int, first: int, last: int) -> dict[int, str]:
    s = path.read_text(encoding="utf-8")
    start = s.find(f"\\c {chapter}")
    end = s.find(f"\\c {chapter + 1}", start + 1)
    body = s[start: end if end > 0 else len(s)]
    out: dict[int, str] = {}
    for m in re.finditer(r"\\v (\d+) (.*?)(?=\\v \d+ |\Z)", body, re.S):
        v = int(m.group(1))
        if first <= v <= last:
            t = re.sub(r"\\f .*?\\f\*", "", m.group(2), flags=re.S)       # footnotes
            t = re.sub(r"\\w ([^|\\]*)\|[^\\]*\\w\*", r"\1", t)            # word attributes
            t = re.sub(r"\\[a-z0-9]+\*?", "", t)                          # remaining markers
            out[v] = " ".join(t.split())
    return out


def align(work_dir: Path) -> list[str]:
    m = yaml.safe_load((work_dir / "manifest.yaml").read_text())
    pl = m["pilot"]
    prefix = m["prefix"]
    written = []
    for t in m.get("translations", []):
        if t.get("format") != "usfm":
            continue
        vs = verses(work_dir / t["file"], pl["chapter"], pl["first"], pl["last"])
        doc = {"translation": t["id"], "aligned_by": "automatic: verse numbers (weft align)",
               "spans": [{"lines": [f"{prefix}.{pl['chapter']}.{v}"] * 2, "text": vs[v]} for v in sorted(vs)]}
        out = work_dir / "sense" / f"{t['id']}.yaml"
        out.write_text(f"# Generated by `weft align` from {t['file']}. Verbatim verse text.\n"
                       + yaml.dump(doc, allow_unicode=True, sort_keys=False, width=200))
        written.append(str(out.relative_to(work_dir)))
    return written
